### ISSUE TITLE
ForestBorne : All items tagged "unusable (Plant Lover)"  

### ISSUE THREAD

**Issue by FlyingVillager** [Clark919/AdaptedOrigins#3]
As stated all items are tagged as unusable due to the Plant Lover Con.  It's supposed to prevent the player from eating plant based foods but now prevents use of anything with this tag (i.e. Fishing Poles, Eggs, Snowballs, Buckets, Books, Bows, Equipping Armor ect.)  if you have to right click to use an item that doesn't interact directly with a block or entity you cannot use it.  You can however eat meats as intended. 
 If this can't be fixed in the next couple weeks I'd appreciate a response saying so as me and my friends are using the mod for story based skyblock and I'd like to be able to participate in the set activities.  If I need to change class now I'd would like a heads up thanks  

![2023-04-03_17 33 53](https://user-images.githubusercontent.com/129798966/229632636-1aa548b1-26ed-476e-b27a-201525f04b23.png)

**Comment by Clark919** [comment]
Had this issue reported by several others as well. Should be an easy fix which I can get around to when I find some free time. I'm aiming to update the modpack once a month to roll out new features from mods within the pack, so I'll aim to fix this within the week.

**Comment by Clark919** [comment]
Fixed in version 1.19-2.3.0.
